# Generated by Django 5.2.11 on 2026-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Выставляйте предметы, находите выгодные предложения и мгновенно выходите на связь с продавцами через встроенный чат.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='BAZAR — торговая площадка по вашей игре', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_item1',
            field=models.CharField(default='Вход через Discord — не нужны отдельные логины.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_item2',
            field=models.CharField(default='Гибкие категории под вашу игру: броня, шлемы, нагрудная броня и другое.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_item3',
            field=models.CharField(default='Личные диалоги по каждому объявлению.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_item4',
            field=models.CharField(default='Можно настроить внешний вид BAZAR под свой стиль.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_title',
            field=models.CharField(default='Как это работает', max_length=100),
        ),
    ]
