# Generated by Django 5.2.11 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_sitesettings_hero_subtitle_sitesettings_hero_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='barter_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='barter_for',
            field=models.ManyToManyField(blank=True, help_text='На какие типы предметов вы готовы обменять этот товар.', related_name='barter_listings', to='market.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='AUEC', max_length=8),
        ),
    ]
