# Generated by Django 5.2.11 on 2026-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_listing_barter_allowed_listing_barter_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
