# Generated by Django 5.2.11 on 2026-02-27 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_listing_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('game_nickname', models.CharField(blank=True, max_length=100, verbose_name='Ник в игре')),
                ('telegram', models.CharField(blank=True, help_text='Например, @nickname или ссылка', max_length=150, verbose_name='Telegram')),
                ('discord', models.CharField(blank=True, help_text='Например, nickname#0000 или ссылка', max_length=150, verbose_name='Discord')),
                ('steam', models.CharField(blank=True, help_text='Ссылка на профиль Steam', max_length=200, verbose_name='Steam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
