# Generated by Django 5.2.11 on 2026-02-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='market.listing'),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='market.listing'),
        ),
    ]
