# Generated by Django 5.2.11 on 2026-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_userprofile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок (необязательно)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка баннера')),
                ('link_url', models.URLField(blank=True, help_text='При клике откроется эта ссылка. Можно оставить пустым.', verbose_name='Ссылка (необязательно)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
