# Generated by Django 5.2.11 on 2026-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('twitch', 'Twitch'), ('vk', 'VK'), ('youtube', 'YouTube'), ('other', 'Другое')], default='telegram', max_length=20, verbose_name='Платформа')),
                ('link_url', models.URLField(help_text='Ссылка на пост или канал', verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
