# Generated by Django 5.2.11 on 2026-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка превью для ссылки, если нужно показать обложку.', null=True, upload_to='news_previews/', verbose_name='Превью (опционально)'),
        ),
    ]
