# Generated by Django 5.2.11 on 2026-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_newsitem_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ссылка на профиль Instagram', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitch',
            field=models.CharField(blank=True, help_text='Ссылка на Twitch‑канал', max_length=200, verbose_name='Twitch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube',
            field=models.CharField(blank=True, help_text='Ссылка на YouTube‑канал', max_length=200, verbose_name='YouTube'),
        ),
    ]
