# Generated by Django 5.2.11 on 2026-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_userprofile_instagram_userprofile_twitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guarantor_description',
            field=models.TextField(blank=True, help_text='Краткая информация о гаранте, опыте и правилах работы.', verbose_name='Описание (для гаранта)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guarantor_priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения (чем выше, тем раньше)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guarantor_title',
            field=models.CharField(blank=True, help_text='Например: Основной гарант, Админ сервера и т.д.', max_length=150, verbose_name='Заголовок/роль (для гаранта)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guarantor',
            field=models.BooleanField(default=False, verbose_name='Показывать в разделе гарантов'),
        ),
    ]
