# Generated by Django 5.2.11 on 2026-02-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_userprofile_guarantor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковиков, можно оставить пустым.', max_length=320, verbose_name='SEO: Описание'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Через запятую: игра, броня, шлем, услуги и т.д.', max_length=320, verbose_name='SEO: Ключевые слова'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто — будет использоваться обычное название объявления.', max_length=160, verbose_name='SEO: Заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_description',
            field=models.CharField(blank=True, help_text='Краткое описание сайта для поисковиков (до ~160–320 символов).', max_length=320, verbose_name='SEO: Description по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, help_text='Через запятую: торговая площадка, игровые услуги, AUEC и т.д.', max_length=320, verbose_name='SEO: Ключевые слова по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым — будет использоваться название сайта.', max_length=160, verbose_name='SEO: Title по умолчанию'),
        ),
    ]
