# Generated by Django 5.2.11 on 2026-02-27 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_listing_seo_description_listing_seo_keywords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='guarantor',
            field=models.ForeignKey(blank=True, help_text='Пользователь‑гарант, который сопровождает эту сделку.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_listings', to=settings.AUTH_USER_MODEL, verbose_name='Гарант по сделке'),
        ),
    ]
