# Generated by Django 5.2.11 on 2026-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_listing_guarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Первая цена при публикации'),
        ),
    ]
