# Generated by Django 5.2.11 on 2026-02-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_listing_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='listing_videos/', verbose_name='Видео')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='market.listing')),
            ],
            options={
                'verbose_name': 'Видео объявления',
                'verbose_name_plural': 'Видео объявлений',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
