# Generated by Django 5.2.11 on 2026-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_listingvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_is_video',
            field=models.BooleanField(default=False, help_text='Включите, если загружен видеофайл для фона.', verbose_name='Фон — это видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_media',
            field=models.FileField(blank=True, help_text='Можно загрузить изображение, GIF или видео для фона сайта.', null=True, upload_to='backgrounds/', verbose_name='Фон сайта (картинка / видео)'),
        ),
    ]
