# Generated by Django 5.2.11 on 2026-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_sitesettings_background_is_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='URL')),
                ('column', models.PositiveSmallIntegerField(choices=[(1, 'Колонка 1'), (2, 'Колонка 2'), (3, 'Колонка 3')], default=1, verbose_name='Колонка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
                'ordering': ['column', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitch', 'Twitch'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('twitter', 'Twitter / X'), ('vk', 'VK')], max_length=20, verbose_name='Соцсеть')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col1_title',
            field=models.CharField(blank=True, help_text='Например: BAZAR, название игры и т.п.', max_length=100, verbose_name='Заголовок первой колонки футера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col2_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок второй колонки футера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col3_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок третьей колонки футера'),
        ),
    ]
