# Generated by Django 5.2.11 on 2026-02-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_footerlink_footersociallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_status_override',
            field=models.CharField(blank=True, choices=[('', 'Авто (по заказам и рейтингу)'), ('basic', 'Обычный'), ('verified', 'Проверенный продавец'), ('silver', 'Серебряный продавец'), ('gold', 'Золотой продавец'), ('cosmic', 'Космический продавец')], help_text='Если выбран, статус продавца на сайте будет именно таким, независимо от количества заказов.', max_length=20, verbose_name='Фиксированный статус продавца'),
        ),
    ]
