# Generated by Django 5.2.11 on 2026-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_userprofile_seller_status_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_left',
            field=models.CharField(default='© BAZAR 2026', help_text='Например: © BAZAR 2026', max_length=255, verbose_name='Текст слева в подвале'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_right',
            field=models.CharField(default='Bazar by Louis Rocket', help_text='Например: "Bazar by Louis Rocket"', max_length=255, verbose_name='Текст справа в подвале'),
        ),
    ]
