# Generated by Django 5.2.11 on 2026-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_sitesettings_footer_left_sitesettings_footer_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(choices=[('sell', 'Продаю'), ('buy', 'Покупаю')], default='sell', help_text='Выберите, вы продаёте товар или хотите его купить.', max_length=8, verbose_name='Тип объявления'),
        ),
    ]
