# Generated by Django 5.2.11 on 2026-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_listing_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(choices=[('sell', 'Продаю'), ('buy', 'Покупаю'), ('trade', 'Обмен')], default='sell', help_text='Выберите, вы продаёте товар или хотите его купить.', max_length=8, verbose_name='Тип объявления'),
        ),
    ]
