# Generated by Django 5.2.11 on 2026-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_alter_listing_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.CharField(blank=True, help_text='Кратко укажите причину блокировки (видно только в админке).', max_length=255, verbose_name='Причина бана'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Если включено, пользователь не сможет пользоваться сайтом.', verbose_name='Заблокирован'),
        ),
    ]
