# Generated by Django 5.2.11 on 2026-03-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_globalchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='market.globalchatmessage', verbose_name='Ответ на сообщение'),
        ),
    ]
