# Generated by Django 5.2.11 on 2026-03-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_globalchatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_home_banner',
            field=models.BooleanField(default=True, help_text='Если выключено — правый баннер с картинкой скрыт, общий чат остаётся.', verbose_name='Показывать баннер на главной'),
        ),
    ]
