# Generated by Django 5.2.11 on 2026-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_sitesettings_show_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_in_hero',
            field=models.BooleanField(default=True, verbose_name='Показывать в большом баннере'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_under_categories',
            field=models.BooleanField(default=False, verbose_name='Показывать под категориями'),
        ),
    ]
