# Generated by Django 5.2.11 on 2026-03-02 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_message_image_alter_message_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('first_path', models.CharField(blank=True, max_length=512)),
                ('last_path', models.CharField(blank=True, max_length=512)),
                ('first_referrer', models.CharField(blank=True, max_length=512)),
                ('last_referrer', models.CharField(blank=True, max_length=512)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия посещения',
                'verbose_name_plural': 'Сессии посещений',
                'ordering': ['-last_seen'],
            },
        ),
    ]
