# Generated by Django 5.2.11 on 2026-03-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_visitsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_news_block',
            field=models.BooleanField(default=True, help_text='Если выключено — карточки новостей и соцсетей на главной скрыты.', verbose_name='Показывать блок новостей'),
        ),
    ]
