# Generated by Django 5.2.11 on 2026-03-11 13:02

import market.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_sitesettings_show_news_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.CharField(blank=True, help_text='Например: Готово к самовывозу, Под заказ и т.д.', max_length=200, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, help_text='Местонахождение товара (например, станция, система).', max_length=200, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='listing',
            name='source',
            field=models.CharField(blank=True, help_text='Например: Разграблено, Куплено, Крафт и т.д.', max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='listing',
            name='star_system',
            field=models.CharField(blank=True, help_text='Звёздная система, где находится товар.', max_length=100, verbose_name='Звёздная система'),
        ),
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='operator',
            field=models.CharField(blank=True, help_text='Название организации или корпорации (например, Omicron Heavy Industries Group).', max_length=200, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, help_text='Например: английский, русский.', max_length=100, verbose_name='Предпочитаемый язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Например: Я онлайн в основном по UTC +13 часов.', max_length=300, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[market.validators.ImageUploadValidator()], verbose_name='Картинка баннера'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listing_images/', validators=[market.validators.ImageUploadValidator()]),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[market.validators.ImageUploadValidator()], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка превью для ссылки, если нужно показать обложку.', null=True, upload_to='news_previews/', validators=[market.validators.ImageUploadValidator()], verbose_name='Превью (опционально)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[market.validators.ImageUploadValidator()], verbose_name='Аватар'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller'], name='listing_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='listing_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listing_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listing_status_idx'),
        ),
    ]
