# Generated by Django 5.2.11 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_add_listing_card_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Отметьте, если товар доступен для продажи.', verbose_name='Товар в наличии'),
        ),
    ]
