# Generated by Django 5.2.11 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_add_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='barter_custom',
            field=models.CharField(blank=True, help_text='Напишите свои варианты через запятую, если нет подходящих категорий.', max_length=500, verbose_name='Свои варианты обмена'),
        ),
    ]
