# Generated by Django 5.2.11 on 2026-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_add_barter_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Сколько штук в наличии (оставьте пустым, если не важно).', null=True, verbose_name='Количество'),
        ),
    ]
