# Generated by Django 5.2.11 on 2026-03-11 14:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_price_history(apps, schema_editor):
    """Заполняем историю цен для существующих объявлений."""
    Listing = apps.get_model("market", "Listing")
    ListingPriceHistory = apps.get_model("market", "ListingPriceHistory")
    for listing in Listing.objects.all():
        initial_price = listing.original_price or listing.price
        if initial_price is None:
            continue
        ListingPriceHistory.objects.create(
            listing=listing,
            price=initial_price,
            recorded_at=listing.created_at,
        )
        if listing.price != initial_price and listing.updated_at != listing.created_at:
            ListingPriceHistory.objects.create(
                listing=listing,
                price=listing.price,
                recorded_at=listing.updated_at,
            )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_add_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.listing')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.RunPython(backfill_price_history, reverse_backfill),
    ]
