# Generated by Django 5.2.11 on 2026-03-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_backfill_price_history'),
        ('market', '0039_add_purchase_request'),
    ]

    operations = [
    ]
