# Generated by Django 5.2.11 on 2026-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_merge_20260313_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='org_url',
            field=models.CharField(blank=True, help_text='Например: https://robertsspaceindustries.com/orgs/INM', max_length=255, verbose_name='Ссылка на организацию RSI'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_left',
            field=models.CharField(default='© StarBaz 2026', help_text='Например: © BAZAR 2026', max_length=255, verbose_name='Текст слева в подвале'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_right',
            field=models.CharField(default='StarBaz by Louis Rocket', help_text='Например: "Bazar by Louis Rocket"', max_length=255, verbose_name='Текст справа в подвале'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='StarBaz — игровая торговая площадка', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='StarBaz — торговая площадка по вашей игре', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='how_it_works_item4',
            field=models.CharField(default='Можно настроить внешний вид StarBaz под свой стиль.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(default='StarBaz', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='StarBaz', max_length=100),
        ),
    ]
