# Generated by Django 5.2.11 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_userprofile_org_url_alter_sitesettings_footer_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='org_logo_url',
            field=models.CharField(blank=True, help_text='Прямая ссылка на логотип (PNG) вашей организации на RSI.', max_length=255, verbose_name='Логотип организации RSI'),
        ),
    ]
