# Generated by Django 5.2.11 on 2026-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_userprofile_org_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_streamer',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является стримером — на карточке продавца появится анимированная плашка.', verbose_name='Стример'),
        ),
    ]
