# Generated by Django 5.2.11 on 2026-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_userprofile_is_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_link',
            field=models.CharField(blank=True, help_text='Любая дополнительная ссылка (на продукт, сайт, портфолио и т.п.).', max_length=200, verbose_name='Дополнительная ссылка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk',
            field=models.CharField(blank=True, help_text='Ссылка на профиль или сообщество ВКонтакте', max_length=200, verbose_name='VK'),
        ),
    ]
