# Generated by Django 5.2.11 on 2026-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_userprofile_extra_link_userprofile_vk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(default='О нас', max_length=120, verbose_name='Футер: название ссылки «О нас»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_url',
            field=models.URLField(blank=True, help_text='URL страницы с описанием проекта.', verbose_name='Футер: ссылка «О нас»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_disclaimer',
            field=models.TextField(blank=True, default='Данный сайт является частным проектом одного из игроков Star Citizen. Администрация игры Cloud Imperium Games, её разработчики, издатель и другие официальные лица, причастные к созданию игры, не имеют никакого отношения к данному сайту.', help_text='Текст про частный проект и отсутствие связи с CIG.', verbose_name='Текст дисклеймера внизу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_discord_title',
            field=models.CharField(default='Discord', max_length=120, verbose_name='Футер: название ссылки на Discord'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_discord_url',
            field=models.URLField(blank=True, verbose_name='Футер: ссылка на Discord'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra1_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Футер: дополнительная ссылка 1 — название'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra1_url',
            field=models.URLField(blank=True, verbose_name='Футер: дополнительная ссылка 1 — URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra2_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Футер: дополнительная ссылка 2 — название'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra2_url',
            field=models.URLField(blank=True, verbose_name='Футер: дополнительная ссылка 2 — URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra3_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Футер: дополнительная ссылка 3 — название'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra3_url',
            field=models.URLField(blank=True, verbose_name='Футер: дополнительная ссылка 3 — URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_privacy_title',
            field=models.CharField(default='Политика конфиденциальности', max_length=160, verbose_name='Футер: название ссылки «Политика конфиденциальности»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_privacy_url',
            field=models.URLField(blank=True, verbose_name='Футер: ссылка на политику конфиденциальности'),
        ),
    ]
