# Generated by Django 5.2.11 on 2026-03-13 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0045_sitesettings_footer_about_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_project_admin',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является администратором площадки (получает обращения из формы поддержки и может помогать пользователям).', verbose_name='Администратор проекта'),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(blank=True, help_text='E‑mail, Discord, Telegram или любая удобная ссылка.', max_length=255, verbose_name='Контакт для ответа')),
                ('request_type', models.CharField(choices=[('product', 'Найти / запросить товар'), ('bug', 'Сообщить о баге'), ('idea', 'Предложение по улучшению'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип обращения')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Кратко о чём')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обращение обработано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
                'ordering': ['-created_at'],
            },
        ),
    ]
