# Generated by Django 5.2.11 on 2026-03-13 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0046_userprofile_is_project_admin_supportrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время ответа администрации'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='admin_replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_replies_made', to=settings.AUTH_USER_MODEL, verbose_name='Администратор, ответивший'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Ответ, который увидит пользователь в своём кабинете поддержки.', verbose_name='Ответ администрации'),
        ),
    ]
