# Generated by Django 5.2.11 on 2026-03-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_supportfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Если включено — у пользователя активен премиум‑статус.', verbose_name='Премиум‑статус активен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_until',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания премиум‑статуса. Можно оставить пустым для бессрочного.', null=True, verbose_name='Премиум действует до'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('product', 'Найти / запросить товар'), ('bug', 'Сообщить о баге'), ('idea', 'Предложение по улучшению'), ('premium', 'Покупка премиум‑статуса'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип обращения'),
        ),
    ]
