# Generated by Django 5.2.11 on 2026-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_userprofile_is_premium_userprofile_premium_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boosted_until',
            field=models.DateTimeField(blank=True, help_text='Если указано будущее время — объявление показывается выше остальных и подсвечивается.', null=True, verbose_name='Поднято в топ до'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_boost_credits',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз пользователь может поднять свои объявления в топ. Доступно только при активном премиум‑статусе.', verbose_name='Очки поднятия объявлений'),
        ),
    ]
