# Generated by Django 5.2.11 on 2026-03-13 13:31

import django.db.models.deletion
import market.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_listing_boosted_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_disclaimer',
            field=models.TextField(blank=True, default='Данный сайт является частным проектом одного из игроков Star Citizen. Администрация игры Cloud Imperium Games, её разработчики, издатель и другие официальные лица, причастные к созданию игры, не имеют никакого отношения к данному сайту. Сайт не выставляет реальные рыночные котировки, не является финансовой, инвестиционной или банковской организацией, не относится к МММ‑подобным проектам и не осуществляет торговлю криптовалютой или настоящими деньгами.', help_text='Текст про частный проект, отсутствие связи с CIG и отсутствие финансовых/инвестиционных услуг.', verbose_name='Текст дисклеймера внизу'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего ответа администрации'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Краткий итоговый ответ, который увидит пользователь в своём кабинете поддержки.', verbose_name='Ответ администрации (кратко)'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Если тикет закрыт, переписка в нём недоступна.', verbose_name='Обращение обработано'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('product', 'Найти / запросить товар'), ('bug', 'Сообщить о баге'), ('idea', 'Предложение по улучшению'), ('seller', 'Вопрос по продавцу / сделке'), ('premium', 'Премиум / оплата'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип обращения'),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='support_screenshots/', validators=[market.validators.ImageUploadValidator()], verbose_name='Скриншот')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.supportrequest', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Сообщение тикета',
                'verbose_name_plural': 'Сообщения тикетов',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
