# Generated by Django 5.2.11 on 2026-03-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_alter_sitesettings_footer_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_body',
            field=models.TextField(blank=True, help_text='При наличии этого текста страница «О нас» будет выводить его как HTML.', verbose_name='Страница «О нас» — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_legal_text',
            field=models.TextField(blank=True, help_text='Текст в попапе при регистрации. Можно использовать HTML‑разметку.', verbose_name='Регистрация — юридический текст'),
        ),
    ]
