# Generated by Django 5.2.11 on 2026-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0053_alter_sellerreview_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_bonus_given',
            field=models.BooleanField(default=False, help_text='Служебное поле: помогает один раз выдать бонусные очки при достижении статуса «Проверенный».', verbose_name='Бонус за статус «Проверенный» выдан'),
        ),
    ]
