# Generated by Django 5.2.11 on 2026-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_userprofile_verified_bonus_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображается в плеере.', max_length=200, verbose_name='Название трека')),
                ('file', models.FileField(help_text='MP3, OGG или другой поддерживаемый браузером формат.', upload_to='music/', verbose_name='Аудиофайл')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше — выше в плейлисте.', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Выключенные треки не показываются в плеере.', verbose_name='Включён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
