# Generated by Django 5.2.11 on 2026-03-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0055_add_music_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecaptchaAdminKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(blank=True, help_text='Публичный ключ из консоли Google reCAPTCHA (тип v2 «Я не робот»).', max_length=200, verbose_name='Ключ сайта (site key)')),
                ('secret_key', models.CharField(blank=True, help_text='Секретный ключ из той же пары. Хранится в базе; доступ только у staff.', max_length=200, verbose_name='Секретный ключ (secret key)')),
            ],
            options={
                'verbose_name': 'Ключи reCAPTCHA (вход в админку)',
                'verbose_name_plural': 'Ключи reCAPTCHA (вход в админку)',
            },
        ),
        migrations.AlterModelOptions(
            name='footersociallink',
            options={'ordering': ['sort_order', 'network'], 'verbose_name': 'Соцсеть в футере', 'verbose_name_plural': 'Соцсети в футере'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
    ]
