# Generated by Django 5.2.11 on 2026-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_recaptcha_admin_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin_whitelist',
            field=models.BooleanField(default=False, help_text='Если включено — пользователь сможет входить в Django Admin (по прямой ссылке /admin/).', verbose_name='Белый список админов'),
        ),
    ]
