# Generated by Django 5.2.11 on 2026-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_userprofile_is_admin_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_operator',
            field=models.BooleanField(default=False, help_text='Оператор может отвечать на обращения, а также выдавать премиум и статусы пользователям.', verbose_name='Оператор (поддержка/премиум)'),
        ),
    ]
