# Generated by Django 5.2.11 on 2026-03-25 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0058_operator_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия тикета'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_closed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрыл тикет'),
        ),
    ]
