# Generated by Django 5.2.11 on 2026-03-25 09:52

from django.db import migrations, models


def create_default_useful_links(apps, schema_editor):
    UsefulLink = apps.get_model("market", "UsefulLink")

    if UsefulLink.objects.exists():
        return

    defaults = [
        (
            "Страница моего Industrial Model в RSI",
            "https://robertsspaceindustries.com/en/orgs/INM",
            "Организация INM на официальном сайте RSI.",
            "bi bi-rocket-takeoff",
        ),
        (
            "База кораблей",
            "https://starcitizen.tools/Ships",
            "Список кораблей и характеристик (Star Citizen Tools).",
            "bi bi-airplane-engines",
        ),
        (
            "База крафта (Crafter)",
            "https://crafter.infinityfreeapp.com/",
            "Крафт и рецепты (инструмент сообщества).",
            "bi bi-tools",
        ),
        (
            "База крафта (SCMDB)",
            "https://scmdb.net/",
            "База данных предметов/крафта (SCMDB).",
            "bi bi-database",
        ),
        (
            "DPS калькулятор (Erkul)",
            "https://www.erkul.games/live/calculator",
            "Фитинг, оружие и подсчёт DPS.",
            "bi bi-speedometer2",
        ),
        (
            "Альтернативный DPS калькулятор (Hardpoint)",
            "https://hardpoint.io/#/",
            "Альтернативный калькулятор по вооружению и DPS.",
            "bi bi-bullseye",
        ),
        (
            "Подменные корабли за концепты (Loaner Ship Matrix)",
            "https://support.robertsspaceindustries.com/hc/en-us/articles/360003093114-Loaner-Ship-Matrix",
            "Список loaner-кораблей от CIG/RSI.",
            "bi bi-diagram-3",
        ),
        (
            "Торговля (маршруты и цены)",
            "https://sc-trade.tools/home",
            "Торговые маршруты, цены, прибыль.",
            "bi bi-graph-up-arrow",
        ),
        (
            "База ресурсов",
            "https://regolith.rocks/survey/ores",
            "Руды, ресурсы и информация по добыче.",
            "bi bi-gem",
        ),
        (
            "База предметов",
            "https://finder.cstone.space/",
            "Поиск предметов и лута по локациям.",
            "bi bi-search",
        ),
        (
            "Поисковик локаций",
            "https://verseguide.com/",
            "Локации, POI и навигация.",
            "bi bi-compass",
        ),
        (
            "Статус серверов RSI",
            "https://status.robertsspaceindustries.com/affected/persistent-universe/index.html",
            "Актуальный статус Persistent Universe.",
            "bi bi-activity",
        ),
        (
            "Русификатор игры",
            "https://www.expanseunion.com/sc/locru",
            "Локализация / русификатор от сообщества.",
            "bi bi-translate",
        ),
    ]

    for idx, (title, url, description, icon_class) in enumerate(defaults, start=10):
        UsefulLink.objects.create(
            title=title,
            url=url,
            description=description,
            icon_class=icon_class,
            sort_order=idx,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_support_resolved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка (URL)')),
                ('description', models.CharField(blank=True, max_length=220, verbose_name='Описание (кратко)')),
                ('icon_class', models.CharField(blank=True, help_text='Например: bi bi-link-45deg или bi bi-rocket-takeoff', max_length=64, verbose_name='Иконка (Bootstrap Icons)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='useful_links_intro',
            field=models.TextField(blank=True, help_text='Вводный текст над списком полезных ссылок. Можно использовать HTML‑разметку.', verbose_name='Полезные ссылки — текст страницы'),
        ),
        migrations.RunPython(create_default_useful_links, migrations.RunPython.noop),
    ]
