# Generated by Django 5.2.11 on 2026-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0061_useful_links_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='operator',
            field=models.CharField(blank=True, help_text='Название организации или корпорации (например, Industrial Model / Omicron Heavy Industries Group).', max_length=200, verbose_name='Организация'),
        ),
    ]
