# Generated by Django 5.2.11 on 2026-03-25 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0062_rename_operator_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='against_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests_against', to=settings.AUTH_USER_MODEL, verbose_name='На кого жалоба'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='dispute_details',
            field=models.TextField(blank=True, verbose_name='Детали спора'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='dispute_kind',
            field=models.CharField(blank=True, choices=[('not_received', 'Не выдали / не вернули'), ('rules_violation', 'Сделка не по правилам'), ('scam', 'Обман / мошенничество'), ('other', 'Другое')], max_length=24, verbose_name='Тип спора'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='related_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='market.conversation', verbose_name='Связанный диалог'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='related_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='market.listing', verbose_name='Связанное объявление'),
        ),
    ]
