# Generated by Django 5.2.11 on 2026-03-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0063_support_disputes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='related_purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='market.purchaserequest', verbose_name='Связанный запрос на покупку'),
        ),
    ]
