# Generated by Django 5.2.11 on 2026-03-25 14:39

import market.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0065_sitesettings_captcha_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='banners/', validators=[market.validators.ImageUploadValidator()], verbose_name='Картинка баннера'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='listing_images/', validators=[market.validators.ImageUploadValidator()]),
        ),
        migrations.AlterField(
            model_name='listingvideo',
            name='file',
            field=models.FileField(max_length=500, upload_to='listing_videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='chat_images/', validators=[market.validators.ImageUploadValidator()], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='file',
            field=models.FileField(help_text='MP3, OGG или другой поддерживаемый браузером формат.', max_length=500, upload_to='music/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка превью для ссылки, если нужно показать обложку.', max_length=500, null=True, upload_to='news_previews/', validators=[market.validators.ImageUploadValidator()], verbose_name='Превью (опционально)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_media',
            field=models.FileField(blank=True, help_text='Можно загрузить изображение, GIF или видео для фона сайта.', max_length=500, null=True, upload_to='backgrounds/', verbose_name='Фон сайта (картинка / видео)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/', validators=[market.validators.ImageUploadValidator()], verbose_name='Аватар'),
        ),
    ]
