"""
Django settings for bazar_site project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file() -> None:
    """
    Подхватываем переменные из файла .env в корне проекта (без сторонних пакетов).
    Уже заданные в ОС переменные не перезаписываем.
    """
    path = BASE_DIR / ".env"
    if not path.is_file():
        return
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=!rd+p94h4rurc*)@!0$!(-pkeek+a#=#&dtxuhw^2b2ul7@&t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Для локальной разработки и для показа через туннели (Cloudflare/ngrok).
# В продакшене используй `settings_prod.py` и задай конкретные домены.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".trycloudflare.com",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://*.trycloudflare.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'widget_tweaks',
    'rest_framework',
    'axes',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.discord',
    'market.apps.MarketConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # На время разработки можно держать собственный rate limit выключенным.
    # В продакшене дополнительно включим Axes (см. блок в конце файла).
    # 'market.middleware.RateLimitMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'market.middleware.AdminWhitelistMiddleware',
    'market.ban_middleware.BanCheckMiddleware',
    'market.middleware.VisitTrackingMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bazar_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'market.context_processors.footer',
            ],
        },
    },
]

WSGI_APPLICATION = 'bazar_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

if DB_ENGINE in ("postgres", "postgresql"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "bazar_db"),
            "USER": os.getenv("DB_USER", "bazar_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
elif DB_ENGINE == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "bazar_db"),
            "USER": os.getenv("DB_USER", "bazar_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            # SQLite может выдавать "database is locked" при параллельных запросах (туннели/статистика/админка).
            # Увеличиваем таймаут ожидания блокировки.
            "OPTIONS": {"timeout": 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Настройки allauth: разрешаем логин по e-mail и имени пользователя
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
# Включаем обязательное подтверждение e‑mail, чтобы не плодился спам-аккаунтов.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# Кастомные формы allauth: CAPTCHA только на регистрации
ACCOUNT_FORMS = {
    "signup": "market.forms.SignupFormWithCaptcha",
}

# Полностью отключаем встроенный rate limit allauth — у нас уже есть
# собственное ограничение через django-axes и (в проде) своим middleware.
# В новых версиях allauth нужно явно задать None для нужных действий.
ACCOUNT_RATE_LIMITS = {
    "change_password": None,
    "change_phone": None,
    "manage_email": None,
    "reset_password": None,
    "reauthenticate": None,
    "reset_password_from_key": None,
    "signup": None,
    "login": None,
    "request_login_code": None,
    "login_failed": None,
    "confirm_email": None,
    "verify_phone": None,
}
# Для старых версий (устаревший способ, на всякий случай тоже глушим):
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = None
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = None

# Пока можно писать письма в консоль. Для боевого сервера нужно
# заменить этот backend на SMTP и настроить учётные данные.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Базовые настройки безопасности для защиты от спуфинга и атак
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"

# Google reCAPTCHA v2 (checkbox «Я не робот») для страницы входа в /admin/
# Приоритет: запись в админке «Ключи reCAPTCHA (вход в админку)», иначе .env / окружение.
# Консоль ключей: https://www.google.com/recaptcha/admin (тип v2)
RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY", "").strip()
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "").strip()

# Настройки django-axes (защита от брутфорса и флуда логина).
# В продакшене включается автоматически, в DEBUG — выключен.
AXES_ENABLED = not DEBUG
AXES_FAILURE_LIMIT = 5              # попыток логина
AXES_COOLOFF_TIME = 1              # часы до сброса счётчика
AXES_LOCKOUT_CALLABLE = None
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

if not DEBUG:
    # В продакшене включаем Axes и дополнительные защиты.
    # Axes middleware должен стоять перед AuthenticationMiddleware.
    if 'axes.middleware.AxesMiddleware' not in MIDDLEWARE:
        auth_index = MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware')
        MIDDLEWARE.insert(auth_index, 'axes.middleware.AxesMiddleware')

    if 'axes.backends.AxesStandaloneBackend' not in AUTHENTICATION_BACKENDS:
        AUTHENTICATION_BACKENDS.insert(0, 'axes.backends.AxesStandaloneBackend')

    # Эти настройки автоматически включатся в продакшене
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
